# Plugin made by XiaoJibaZhanshi
# If you have any questions or shit breaks, DM me on discord: szym402pl

# points-per-kill-list-override list functions in format "EntityType:Amount"
# Refer to: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Default values: Player - 200, Passive mob - 10, Monster - 20, Wither/Dragon - 400, Warden: 500

# PlaceholderAPI placeholders:
# Format is %vp_top_X_(SORT_METHOD)% and 'Top 10' positions can be sorted by:
# kills, deaths, passive_mob_kills, aggressive_mob_kills, kd, level, points
# EXAMPLE (top 7 passive mob kill position): %vp_top_7_passive_mob_kills%

# Don't know what placeholders are or how to use them? Refer to: https://wiki.placeholderapi.com/

vp-command:
  stats-permission: "vpsystem.stats"
  reload-permission: "vpsystem.reload"
  stat-reset-permission: "vpsystem.reset" # Use sparingly - don't give it even to admins!

are-perks-cumulative: true

points-per-kill-list-override: [] # Delete brackets if you want to override entity types
#  - "PLAYER:250"
#  - "WARDEN:600"
#  - "PIG:15"

# NOTE: First level is the default, don't remove it
levels:
  1:
    title: "&aScout"
    points:
      to-level-up: 300
      on-death: 0
    perks:
      damage: 0.5
      health: 0.5
  2:
    title: "&aSquire"
    points:
      to-level-up: 300
      on-death: -25 # doesn't matter if you do -25 or 25, it's just a visual clue here
    perks:
      damage: 0.5
      health: 0.5
  3:
    title: "&aKnight"
    points:
      to-level-up: 300
      on-death: -50
    perks:
      damage: 0.5
      health: 0.5